name: Multi-Arch Build

on:
  workflow_dispatch: # لتشغيل البناء يدوياً بضغطة زر

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {os: linux, arch: amd64}
          - {os: linux, arch: arm64}
          - {os: android, arch: arm64}
          - {os: windows, arch: amd64}

    steps:
      - name: Clone Original DNSTT
        run: git clone https://github.com/google/dnstt.git .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o "dnstt-client-${{ matrix.os }}-${{ matrix.arch }}" ./dnstt-client
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o "dnstt-server-${{ matrix.os }}-${{ matrix.arch }}" ./dnstt-server

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: dnstt-${{ matrix.os }}-${{ matrix.arch }}
          path: dnstt-*
